vim.opt.tabstop = 2
vim.opt.softtabstop = 2
vim.opt.expandtab = true
vim.opt.shiftwidth = 2
vim.opt.breakindent = true
vim.opt.incsearch = true
vim.opt.showmatch = true
vim.opt.termguicolors = true
vim.opt.mouse = 'a'
vim.opt.clipboard = 'unnamed,unnamedplus'
vim.opt.winbar = "%=%m %f %r"
vim.opt.backspace = '2'
vim.opt.showcmd = true
vim.opt.laststatus = 2
vim.opt.autowrite = true
vim.opt.cursorline = true
vim.opt.autoread = true
vim.g.mapleader = ' '
vim.g.maplocalleader = ' '
vim.opt.autoindent = true
vim.opt.smartindent = true
vim.opt.hlsearch = true
vim.opt.ignorecase = true
vim.opt.smarttab = true
-- Navigate vim panes better
vim.wo.number = true
vim.opt.splitbelow = true
vim.opt.splitright = true
vim.opt.undofile = true
